name: CI - Test Docker Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build server image
      uses: docker/build-push-action@v4
      with:
        context: ./server
        file: ./server/Dockerfile.dev
        push: false
        tags: test-server:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
