name: Deploy - Push to DockerHub

on:
  workflow_run:
    workflows: ["CI - Test Docker Build"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # needs: [ci]  # This makes the deploy workflow dependent on the successful completion of the CI workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if CI workflow succeeded
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push server image
      uses: docker/build-push-action@v4
      with:
        context: ./server
        file: ./server/Dockerfile.dev
        push: true
        tags: wrlakshan/server:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build and push client image
      uses: docker/build-push-action@v4
      with:
        context: ./client
        file: ./client/Dockerfile.dev
        push: true
        tags: wrlakshan/client:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max